name: ludo_flutter
description: Ludo game with flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  agora_rtc_engine: ^6.0.0-rc.2
  cloud_firestore: ^3.4.9
  firebase_core: ^1.23.0
  firebase_crashlytics: ^2.8.11
  firebase_performance: ^0.8.3+1
  flutter:
    sdk: flutter
  just_audio: ^0.9.29
  provider: ^6.0.3
  simple_ripple_animation: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/dice/
    - assets/images/crown/
    - assets/sounds/
